[package]
name = "binseq"
version = "0.10.0"
edition = "2024"
description = "A high efficiency binary format for sequencing data"
license = "MIT"
authors = ["Noam Teyssier"]
repository = "https://github.com/noamteyssier/binseq"
documentation = "https://docs.rs/binseq"
categories = ["science::bioinformatics", "encoding", "data-structures"]
keywords = ["binary", "nucleotide", "sequencing", "genomics", "fastq"]

[dependencies]
anyhow = { version = "1.0.104", optional = true }
bitnuc-deprec = { package ="bitnuc", version = "0.4.1" }
bitnuc = "0.5.4"
bytemuck = { version = "1.25.2", features = ["derive", "extern_crate_alloc"] }
itoa = "1.0.18"
memmap2 = "0.9.11"
paraseq = { version = "0.5.1", optional = true }
parking_lot = {version = "0.12.5", optional = true }
rand = { version = "0.9.5", features = ["small_rng"] }
sucds = "0.8.3"
thiserror = "2.0.20"
zstd = { version = "0.13.3", features = ["zstdmt"] }

[dev-dependencies]
memchr = "2.8.3"
anyhow = "1.0.104"
parking_lot = "0.12.5"
clap = { version = "4.6.6", features = ["derive"] }
tempfile = "3.27.0"

[features]
default = []
anyhow = ["dep:anyhow"]
paraseq = ["dep:paraseq", "dep:parking_lot"]

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
missing_errors_doc = "allow"
struct_excessive_bools = "allow"
fn_params_excessive_bools = "allow"

[[example]]
name = "auto-write"
required-features = ["paraseq"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
